application:
    title: Project-Common-Service
    version: Version 1
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 8070
    servlet:
        context-path: /project-common
spring:
    application:
        name: Project-Common-Service
    datasource:
        driver:
            class-name: oracle.jdbc.OracleDriver
        password: hr
        url: jdbc:oracle:thin:@localhost:1521:xe
        username: hr
    jackson:
        serialization:
            FAIL_ON_EMPTY_BEANS: false
    jpa:
        database-platform: org.hibernate.dialect.Oracle10gDialect
        hibernate:
            ddl-auto: update
togglz:
    console:
        enabled: true
        path: /togglz-console
        secured: false
        use-management-port: false
    features:
        GET_PROJECT:
            enabled: true
